import type { Locale } from "@/lib/locale";
import type { AuthPageContent } from "@/lib/types";

export const registerContent: Record<Locale, AuthPageContent> = {
  es: {
    title: "Registro - Swap RPG",
    description: "Crea tu cuenta de Swap RPG",
    heading: "Crear cuenta",
    lead: "Regístrate para gestionar tu personaje y contribuir al proyecto.",
    fields: [
      {
        name: "username",
        type: "text",
        label: "Usuario",
        placeholder: "tu nombre de usuario",
        required: true,
        minLength: 3,
        autoComplete: "username",
      },
      {
        name: "email",
        type: "email",
        label: "Correo electrónico",
        placeholder: "correo@ejemplo.com",
        required: true,
        autoComplete: "email",
        inputMode: "email",
      },
      {
        name: "password",
        type: "password",
        label: "Contraseña",
        placeholder: "mínimo 6 caracteres",
        required: true,
        minLength: 6,
        autoComplete: "new-password",
      },
    ],
    submitLabel: "Crear cuenta",
    altLabel: "¿Ya tienes cuenta? Inicia sesión",
    altHref: "/login",
    oauthLabel: "Registrarse con Google",
    oauthDivider: "o",
    errors: {
      "username_taken": "El nombre de usuario ya está en uso",
      "email_taken": "El correo ya está registrado",
      "validation": "Revisa los campos e inténtalo de nuevo",
    },
  },
  en: {
    title: "Register - Swap RPG",
    description: "Create your Swap RPG account",
    heading: "Create account",
    lead: "Register to manage your character and contribute to the project.",
    fields: [
      {
        name: "username",
        type: "text",
        label: "Username",
        placeholder: "your username",
        required: true,
        minLength: 3,
        autoComplete: "username",
      },
      {
        name: "email",
        type: "email",
        label: "Email",
        placeholder: "email@example.com",
        required: true,
        autoComplete: "email",
        inputMode: "email",
      },
      {
        name: "password",
        type: "password",
        label: "Password",
        placeholder: "minimum 6 characters",
        required: true,
        minLength: 6,
        autoComplete: "new-password",
      },
    ],
    submitLabel: "Create account",
    altLabel: "Already have an account? Log in",
    altHref: "/login",
    oauthLabel: "Sign up with Google",
    oauthDivider: "or",
    errors: {
      "username_taken": "Username is already taken",
      "email_taken": "Email is already registered",
      "validation": "Check the fields and try again",
    },
  },
};
